### ISSUE TITLE
CUADRO COMPARATIVO METODO CIENTIFICO

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-irvinjs22620075#1]
![CUADRO COMPARATIVO METODO CIENTIFICO](https://user-images.githubusercontent.com/112287287/187579128-c4b034f5-e7ef-42d7-9163-56670086b573.jpg)

**Comment by 11042002** [comment]
Tu calificación es de: 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
